// Code generated by goctl. DO NOT EDIT.
package types

type BaseMsg struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Page struct {
	CurrentPage int64 `form:"currentPage,default=1"`
	PageSize    int64 `form:"pageSize,default=10"`
}

type LoginUser struct {
	Id       int64  `json:"id"`
	UserName string `json:"userName"`
	RealName string `json:"realName"`
	Avatar   string `json:"avatar"`
	IsAdmin  int64  `json:"isAdmin"`
	Roles    string `json:"roles"`
	Token    string `json:"token"`
}

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseMsg
	UserInfo LoginUser `json:"userInfo"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	BaseMsg
	UserInfo LoginUser `json:"userInfo"`
}
